### ISSUE TITLE
What to do about the missing license?

### ISSUE THREAD

**Issue by Ambrevar** [defunkydrummer/cl-xmlspam#1]
The missing license is annoying.  Technically, it means that this package is non free.  Other important Common Lisp library rely on it, such as https://github.com/death/dbus.

What can we do about it?  I've sent an email to Rog Peppe yesterday, let's see if we get an answer.  Any suggestion?  @defunkydrummer ?

**Comment by Ambrevar** [comment]
The lack of license is a blocker to package XMLSPAM and all its dependents for Guix.

**Comment by leinadlime** [comment]
@defunkydrummer  would be so kind, if you would consider adding a permissive licence.

i (also a huge fan of common lisp) stumpled upon this project,
via the awesome next-browser: https://next.atlas.engineer/
which is also getting distributed via GUIX (also super cool in my perspective),
but not in the main upstream, since of these licence issue...
read here: https://gitlab.com/atlas-engineer/next-guix-channel

would be lovely if this would be solved,..
anyway, much peace and love to you.

**Comment by Ambrevar** [comment]
No news from @rogpeppe in 2 months... :(

**Comment by rogpeppe** [comment]
I created a new fork with a proper license [here](https://github.com/rogpeppe/cl-xmlspam).
Does that work for you?

**Comment by Ambrevar** [comment]
@rogpeppe: This is perfect, thank you so much!  Now Next browser is back in Guix!
